name: reader_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_rust_bridge: 2.11.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  state_notifier: ^1.0.0
  flutter_state_notifier: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  epubx: ^4.0.0
  flutter_html: ^3.0.0
  archive: ^3.6.1
  xml: ^6.5.0
  rust_lib_reader_app:
    path: rust_builder
  uuid: ^4.5.2
  http: ^1.2.2
  flutter_tts: ^4.2.3
  html: ^0.15.4
  hyphenatorx: ^1.5.11
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
  build_runner: ^2.10.4
  json_serializable: ^6.10.0
  hive_ce_generator: ^1.1.0
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 23
  adaptive_icon_background: "#8C1D18"
  adaptive_icon_foreground: "assets/ic_launcher.png"
  remove_alpha_android: true

flutter:

  uses-material-design: true


